name: Callable CRM E2E Tests

on:
  workflow_call:
    inputs:
      e2e_repo:
        required: true
        type: string
        description: "Owner and repo name containing your e2e repo like ultimateai/e2e-tests"
      projects:
        default: "crm-integration"
        required: true
        type: string
        description: "matrix projects"
      e2e_bucket_name:
        required: true
        type: string
        description: "Name of bucket in which to store the crm-tests results"
    outputs:
      bucket_link:
        description: "The link of the bucket containing the zip with the results"
        value: ${{ jobs.announce.outputs.bucket_link }}

env:
  E2E_REPO: ${{ inputs.e2e_repo }}
  BUCKET_NAME: ${{ inputs.e2e_bucket_name }}
  actions: "ai-agents-cd-fe"
  login: "ai-agents-apss-fe"

jobs:
  crm-test:
    runs-on: qe-runners
    if: ${{ always() }}
    permissions:
      contents: "read"
      id-token: "write"
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(inputs.projects) }}
        shardIndex: [1, 2, 3]
        shardTotal: [3]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: "Checkout CRM tests repository"
        uses: actions/checkout@v4
        with:
          repository: ${{ env.E2E_REPO }}
          token: ${{ secrets.QE_TOKEN }}
      - name: Install playwright
        run: npm ci

      - name: Run CRM tests
        run: |
          touch results.log
          echo '```logtalk' >> results.log

          if [ ${{ matrix.shardIndex }} -eq 1 ]; then
            TEST_TAGS="@worker-1"
          elif [ ${{ matrix.shardIndex }} -eq 2 ]; then
            TEST_TAGS="@worker-2"
          elif [ ${{ matrix.shardIndex }} -eq 3 ]; then
            TEST_TAGS="@worker-3"
          fi

          npx playwright test --config ./playwright.config.ts --project=${{ matrix.project }} --grep $TEST_TAGS

          echo '```' >> results.log
        env:
          DASHBOARD_STAGING_ADMIN_USER_PWD: "${{ secrets.DASHBOARD_STAGING_ADMIN_USER_PWD }}"
          DASHBOARD_STAGING_ADMIN_2_USER_PWD: "${{ secrets.DASHBOARD_STAGING_ADMIN_2_USER_PWD }}"
          DASHBOARD_STAGING_ADMIN_3_USER_PWD: "${{ secrets.DASHBOARD_STAGING_ADMIN_3_USER_PWD }}"
          DASHBOARD_STAGING_ADMIN_4_USER_PWD: "${{ secrets.DASHBOARD_STAGING_ADMIN_4_USER_PWD }}"
          SUNSHINE_USER_PWD: "${{ secrets.SUNSHINE_USER_PWD }}"
          SUNSHINE_MESSAGING_USER_PWD: "${{ secrets.SUNSHINE_MESSAGING_USER_PWD }}"
          SUNSHINE_GROUP_USER_PWD: "${{ secrets.SUNSHINE_GROUP_USER_PWD }}"
          SLACK_BOT_USER_OAUTH_TOKEN: "${{ secrets.PLAYWRIGHT_SLACK_BOT_USER_OAUTH_TOKEN }}"
          SUNCO_GROUP_AUTHORISATION_SECRET: "${{ secrets.SUNCO_GROUP_AUTHORISATION_SECRET }}"
          SUNSHINE_AUTHORISATION_SECRET: "${{ secrets.SUNSHINE_AUTHORISATION_SECRET }}"
          ZENDESK_SINGLE_TOUCH_USER_PWD: "${{ secrets.ZENDESK_SINGLE_TOUCH_USER_PWD }}"
          ZENDESK_MULTI_TOUCH_USER_PWD: "${{ secrets.ZENDESK_MULTI_TOUCH_USER_PWD }}"

      - name: Upload blob (shard) reports to GitHub Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: crm-blob-reports-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

  merge-reports:
    if: always()
    needs: crm-test
    runs-on: qe-runners
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci

      - name: Download CRM blob reports from GitHub Artifacts
        if: always()
        id: download_reports
        uses: actions/download-artifact@v4
        with:
          pattern: crm-blob-reports-*
          path: crm-blob-reports
          merge-multiple: true

      - name: Merge into HTML and JSON Report
        id: merge-reports
        if: success() || (failure() && steps.download_reports.outcome == 'success')
        run: >-
          PLAYWRIGHT_JSON_OUTPUT_NAME=results.json npx playwright merge-reports
          --reporter=html,json ./crm-blob-reports

      - name: Upload merged json report to Github Actions Artifacts
        if: success() || (failure() && steps.merge-reports.outcome == 'success')
        uses: actions/upload-artifact@v4
        with:
          name: merged-reports
          path: results.json
          retention-days: 1

      - name: "Google Auth"
        if: always()
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER_NAME }}"
          service_account: "${{ secrets.GSA_QE_EMAIL }}"
          project_id: "${{ env.PROJECT_ID }}"

      - name: Set up Cloud SDK
        if: always()
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "${{ env.PROJECT_ID }}"
          install_components: alpha

      - name: Get current date
        if: always()
        run: |
          currentDate=$(date '+%Y%m%d')
          echo "CURRENT_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV

      - name: Upload CRM test results to GCP bucket
        if: success() || (failure() && steps.merge-reports.outcome == 'success')
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          gzip: false
          path: playwright-report/
          destination: >-
            ${{ env.BUCKET_NAME }}/${{ github.event.repository.name }}/${{
            env.CURRENT_DATE }}/${{ github.run_id }}/deployment/

  announce:
    runs-on: qe-runners
    needs: merge-reports
    if: always()
    outputs:
      bucket_link: ${{ steps.announcement.outputs.bucket_link }}
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - name: Announce in job
        if: always()
        id: announcement
        run: |
          currentDate=$(date '+%Y%m%d')
          echo "Your artifact is in [this gcp bucket](https://console.cloud.google.com/storage/browser/${{ env.BUCKET_NAME }}/${{ github.event.repository.name }}/$currentDate/${{ github.run_id }}/deployment/) " >> $GITHUB_STEP_SUMMARY
          echo "bucket_link=https://console.cloud.google.com/storage/browser/${{ env.BUCKET_NAME }}/${{ github.event.repository.name }}/$currentDate/${{ github.run_id }}/deployment/" >> $GITHUB_OUTPUT
