name: Deploy branch to dev

on:
  workflow_dispatch:
    inputs:
      Branch_name:
        description: 'Which branch you want to build and deploy to dev'
        required: true
        type: string

jobs:
  build_deploy_dev:
    uses: ultimateai/workflows/.github/workflows/deploy-from-branch.yml@0.15.5
    with:
      ###---- Your input variables, ask anything you don't understand, but you can play around ----##
      app_squad: backend #Please update with your squad!
      # npm_install_command: "npm i --no-audit --loglevel verbose" #by default is npm i, but can be modified as shown here. 
      # test_command: "" #By default is npm run test, but testing stage can be disabled if test_command is empty string
      # build_command: "" #By default is npm run build
      # node_version: "16.x" #By default is 16.x.
      # app_names: "dashboard-backend,dashboard-backend-internal,intent-health-checker" #In case of a 1repo to Napps situation, please use app_names and update deployment_env folder
      ###---- Platform input variables, I recommend leaving them untouched.  ----##
      image_repo: eu.gcr.io/ultimateai-169214 
      github_email: 86783263+ultimateai-bot@users.noreply.github.com
      github_user: ultimateai-bot
      k8s_manifests_repo: ultimateai/k8s-manifests
      branch_name: ${{ github.event.inputs.Branch_name }}
      node_version: "18.x"

    secrets: inherit