

name: Manual deploy

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Choose in which environment to deploy your app'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - development
          - production
      Run_e2e_tests:
          description: 'In case of deploying to staging, you can execute e2e test in testim'
          required: true
          default: 'false'
          type: choice
          options:
            - 'false'
            - 'true'


jobs:
  deploy:
    uses: ultimateai/workflows/.github/workflows/manual-deploy.yml@0.15.5
    with:
      ###---- Your input variables, ask anything you don't understand, but you can play around ----##
      app_squad: backend #Please update with your squad!
      slack_channel_id: '#engineering-announcements' #You have to make sure that github-actions-deployments bot is invited to your channel! This field is optional - no field, no slack notif =)
      # app_names: "dashboard-backend,dashboard-backend-internal,intent-health-checker" #In case of a 1repo to Napps situation, please use app_names and update deployment_env folder
      ###---- Platform input variables, I recommend leaving them untouched.  ----##
      image_repo: eu.gcr.io/ultimateai-169214
      environment: ${{ github.event.inputs.Environment }}
      github_email: 86783263+ultimateai-bot@users.noreply.github.com
      github_user: ultimateai-bot
      k8s_manifests_repo: ultimateai/k8s-manifests
      run_e2e_tests: ${{ github.event.inputs.Run_e2e_tests }}
      staging_cluster_name: ultimateai-staging-main-1
      staging_cluster_location: europe-west1
      testim_project: 4j2SxviWIdxspepqscef
      testim_grid: Testim-Grid
      testim_suite: Critical
      testim_additional_flags: "--turbo-mode --parallel 2"
    secrets: inherit
