name: Merged PR to main branch

on:
  pull_request:
    branches:
      - main
    types:
      - closed


jobs:
  merged:
    uses: ultimateai/workflows/.github/workflows/merged-pr.yml@0.15.5
    with:
      ###---- Your input variables, ask anything you don't understand, but you can play around ----##
      app_squad: backend #Please update with your squad!
      update_file: package.json #Optional -- delete for the pipeline to NOT modify your package.json
      changelog: true #Optional -- set to false or delete for the pipeline to NOT modify your changelog
      initial_release: 1.0.0 #Although optional (default is 0.0.1) please make sure to use a version which does NOT step over existing images for your repository
      # node_version: "16.x"
      # npm_install_command: "npm i --no-audit --loglevel verbose" #by default is npm i, but can be modified as shown here. 
      # test_command: "npm run test" #By default is npm run test, but testing stage can be disabled if test_command is empty string
      # lint_command: "npm run lint" ## Customizable, by default is npm run lint, but can be disabled if set to empy string
      # build_command: "npm run build" ## Customizable, by default is npm run build, but can be disabled if set to empy string
      # app_names: "dashboard-backend,dashboard-backend-internal,intent-health-checker" #In case of a 1repo to Napps situation, please use app_names and update deployment_env folder
      # automatic_deployment_to: staging by default, but can also be development, or both - in case of both, just type "development,staging"
      ###---- Platform input variables, I recommend leaving them untouched.  ----##
      image_repo: eu.gcr.io/ultimateai-169214
      github_email: 86783263+ultimateai-bot@users.noreply.github.com
      github_user: ultimateai-bot
      k8s_manifests_repo: ultimateai/k8s-manifests
      node_version: "18.x" 
    secrets: inherit