name: "Open PR to main branch"

on:
 pull_request:
   branches:
     - main

jobs:
  test_build:
    uses: ultimateai/workflows/.github/workflows/ts_open-pr.yml@0.15.5
    with:
    ###---- Your input variables, ask anything you don't understand, but you can play around ----##
      node_version: "18.x"
    #   npm_install_command: "npm i --no-audit --loglevel verbose" ## Customizable, by default is npm i
    #   lint_command: "npm run lint" ## Customizable, by default is npm run lint, but can be disabled if set to empy string
    #   build_command: "npm run build" ## Customizable, by default is npm run build, but can be disabled if set to empy string
    #   test_command: "npm run test" ## Customizable, by default is npm run test, but can be disabled if set to empy string
    secrets: inherit